### ISSUE TITLE
Error when generating a normal map

### ISSUE THREAD

**Issue by hokutonanto** [HugoTini/DeepBump#11]
I'm getting this error when I try to generate a normal map.

`Python: Traceback (most recent call last):
  File "C:\Users\Piero\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\DeepBump-4\__init__.py", line 151, in execute
    output_img = module_color_to_normals.apply(input_img, OVERLAP, self.progress_print)
  File "C:\Users\Piero\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\DeepBump-4\module_color_to_normals.py", line 25, in apply
    tiles, paddings = utils_inference.tiles_split(
  File "C:\Users\Piero\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\DeepBump-4\utils_inference.py", line 44, in tiles_split
    img = pad(img, pad_left, pad_right, pad_top, pad_bottom)
  File "C:\Users\Piero\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\DeepBump-4\utils_inference.py", line 5, in pad
    return np.pad(img, ((0, 0), (top, bottom), (left, right)), mode='wrap')
  File "<__array_function__ internals>", line 180, in pad
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\numpy\lib\arraypad.py", line 814, in pad
    raise ValueError(
ValueError: can't extend empty axis 1 using modes other than 'constant' or 'empty'
`

I'm using Blender 3.4.1
It worked before.

Edit: never mind, now it's working fine.
The texture for some reason wasn't loading properly. After I relinked to the correct path, I was able to generate the normal map as expected.

**Comment by HugoTini** [comment]
Closing this issue since it is working fine now
