### ISSUE TITLE
Traceback error when attempting to generate normal map

### ISSUE THREAD

**Issue by ilaision** [HugoTini/DeepBump#29]
Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\DeepBump-7\__init__.py", line 162, in execute
    output_img = module_color_to_normals.apply(input_img, OVERLAP, self.progress_print)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\DeepBump-7\module_color_to_normals.py", line 36, in apply
    ort_session = ort.InferenceSession(addon_path + "/deepbump256.onnx")
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\DeepBump-7\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\DeepBump-7\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\DeepBump-7\onnxruntime\capi\onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by studiorosarot** [comment]
Same issue here. Running Blender 3.5 as well.

**Comment by HugoTini** [comment]
Duplicate https://github.com/HugoTini/DeepBump/issues/27
