### ISSUE TITLE
Bledner 3.5 error (generate normal map)

### ISSUE THREAD

**Issue by AlexNorth365** [HugoTini/DeepBump#30]
bpy.context.scene.deep_bump_tool.colortonormals_tiles_overlap_enum = 'SMALL'
Python: --- Logging error ---
Traceback (most recent call last):
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/logging/handlers.py", line 74, in emit
    self.doRollover()
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/logging/handlers.py", line 433, in doRollover
    if os.path.exists(dfn):
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Call stack:
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/__init__.py", line 78, in log_exhook
    LookingGlassAddonLogger.critical("An unhandled error occured. Here is the traceback:\n", exc_info=(exc_type, exc_value, exc_traceback))
Message: 'An unhandled error occured. Here is the traceback:\n'
Arguments: ()
Traceback (most recent call last):
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/__init__.py", line 162, in execute
    output_img = module_color_to_normals.apply(input_img, OVERLAP, self.progress_print)
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/module_color_to_normals.py", line 36, in apply
    ort_session = ort.InferenceSession(addon_path + "/deepbump256.onnx")
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
Python: --- Logging error ---
Traceback (most recent call last):
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/logging/handlers.py", line 74, in emit
    self.doRollover()
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/logging/handlers.py", line 433, in doRollover
    if os.path.exists(dfn):
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Call stack:
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/__init__.py", line 78, in log_exhook
    LookingGlassAddonLogger.critical("An unhandled error occured. Here is the traceback:\n", exc_info=(exc_type, exc_value, exc_traceback))
Message: 'An unhandled error occured. Here is the traceback:\n'
Arguments: ()
Traceback (most recent call last):
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/__init__.py", line 162, in execute
    output_img = module_color_to_normals.apply(input_img, OVERLAP, self.progress_print)
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/module_color_to_normals.py", line 36, in apply
    ort_session = ort.InferenceSession(addon_path + "/deepbump256.onnx")
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/DeepBump-7/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by MaxLastBreath** [comment]
Getting the same error here

**Comment by HugoTini** [comment]
Duplicate https://github.com/HugoTini/DeepBump/issues/27
